//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFiller2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Songs
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.TimeSpan Duration { get; set; }
        public int AlbumId { get; set; }
    
        public virtual Albums Albums { get; set; }
    }
}
